apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /home/argocd/kustomize/plugin/kohcojlb.github.com/sops-decrypt/sops-decrypt
          name: kustomize-sops
          subPath: sops-decrypt
      initContainers:
      - name: kustomize-sops
        image: ghcr.io/kohcojlb/kustomize-sops:v0.1.0
        command:
        - cp
        - /sops-decrypt
        - /mnt/
        volumeMounts:
        - mountPath: /mnt
          name: kustomize-sops
      volumes:
      - name: kustomize-sops
        emptyDir: { }
