name: build and push
on:
  push:
    branches:
    - master
    paths:
    - "*.go"
    - go.mod
    - go.sum
    - Dockerfile
    tags:
    - "v*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/kohcojlb/kustomize-sops
        tags: |
          type=ref,event=tag
          type=sha
          type=raw,value=dev,event=branch
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
